name: Build CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  Build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
    
      - name: Get ESP-IDF & build project
        uses: espressif/esp-idf-ci-action@v1
        with: 
          esp_idf_version: v5.5.1
          target: esp32s3
          command: |
            cp sdkconfig.defaults sdkconfig || true
            set -e
            echo "::group::Configure"
            idf.py reconfigure
            echo "::endgroup::"

            echo "::group::Build"
            idf.py build
            echo "::endgroup::"

            echo "::group::Size"
            idf.py size
            echo "::endgroup::"